name: Run Prediksi & Togel Scraper

on:
  workflow_dispatch:   # bisa dijalankan manual dari GitHub UI
  schedule:
    - cron: "0 */3 * * *"   # jalan tiap 3 jam sekali

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 playwright
          playwright install --with-deps chromium

      - name: Run prediksi.py
        run: |
          python prediksi.py

      - name: Run togel.py
        run: |
          python togel.py
